### PR TITLE
simplify tagging

### PR DESCRIPTION
**Pull request by eirnym**

### CODE REVIEW

**Review by hannesa2 — APPROVED** [review]
Let's try it

**Comment by hannesa2** [comment]
From previous release 
image

**Comment by hannesa2** [comment]
My very first pull request was working https://github.com/hannesa2/js2p-gradle/releases/tag/0.2

image

**Comment by hannesa2** [comment]
Please avoid this `v` is tag. It's obsolete

**Comment by eirnym** [comment]
ah, I haven't know that `v` is obsolete in the tag, I'll try again.

**Comment by eirnym** [comment]
> My very first pull request was working https://github.com/hannesa2/js2p-gradle/releases/tag/0.2

so I reverted that part. My bad, that I haven't looked into your repo

**Comment by eirnym** [comment]
And next time I'll write something to fields ;P

**Comment by hannesa2** [comment]
Now it looks better 

image

**Comment by hannesa2** [comment]
We could delete `1.2` and `1.2.1` release and tag from master again. What do you think ?

**Comment by eirnym** [comment]
Yes, let's do it, Actually the new plugin is pending for the review

**Comment by eirnym** [comment]
Zrzut ekranu 2021-03-1 o 15 18 18

**Comment by hannesa2** [comment]
Ho did you made this release ? It still differs from full auto-release

https://github.com/jsonschema2dataclass/js2d-gradle/releases/tag/1.2.2

image

It looks like you did it manually, am I right ?

**Comment by eirnym** [comment]
Yes, I did it via release button. I'm happy to learn about autoreleases

**Comment by hannesa2** [comment]
`git tag -a 1.2.2 -m "Your text"`
`git push --tags`

and you are done

**Comment by eirnym** [comment]
My goodness, it's sooo easy!

**Pull request merged**
