### PR TITLE
Bump jsonschema2dataclass

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by eirnym** [comment]
Strangely enough, version 3.1.0 has been deployed as `0.0.0-git-version`. I'm on investigation

**Comment by hannesa2** [comment]
It's quite easy. Commit 4d532ab29723bfbfaed08f13a96cfb01c94d8714 introduced a way to get version with a variable instead of commit info. This makes a lot of maintenance.
Default is `0.0.0-no-git-version`

I don't like this error prone way

**Comment by eirnym** [comment]
Somebody tempered release.yaml by removing version variable. Re rely on that as it could be a pre-release version which we add into the data

**Comment by hannesa2** [comment]
To be honest, when you relay on a manual set of a variable in CI secrets, this is, to say it friendly, not good

**Comment by eirnym** [comment]
you probably haven't tested changes in commit https://github.com/jsonschema2dataclass/js2d-gradle/commit/31297194395b894219873526c0416facd7fb99b2. The mechanism was from the beginning and it worked well. Only now you're adding another mechanism back in https://github.com/jsonschema2dataclass/js2d-gradle/pull/134. This mechanism worked from command line only for a reason.

I'd prefer to have an ability to release with tagging from GitHub interface as well, not only from the command line. And in this case I'd prefer to tag only after it was actually published.

**Comment by eirnym** [comment]
and returning to that commit do you know the reason, why `VERSION_J=$(echo $VERSION | cut -d'/' -f3)` was set this way?

**Comment by eirnym** [comment]
@hannesa2 how you want to pass a login and password in other way other than CI secret?

**Comment by hannesa2** [comment]
> how you want to pass a login and password in other way other than CI secret?

It has no relation to credentials, it's this

    System.getenv("VERSION")?.let {

**Comment by eirnym** [comment]
There's two other ways to do this (as far as I know):
* get from git tag in `build.gradle`
* pass property like `-Prelease=1.3`  (`version` case sensitive property is the worst one)

Reasons why I'd avoid getting a git tag with self-written function:
- it's quite complicated. Thus maintenance is required 
- language changes could drastically affect this piece of code ant it may become unmaintainable. 

Using git tag by using a plugin is acceptable and easy way. But few months ago all plugins I checked failed with gradle 7.0. 

At work in CI we use property way as we don't know who will support this project in 10 years and which VCS will be used. Why 10 years? Because in huge companies code can survive for decades without any changes beside library updates if a team stretched a budget. 

Do you know any other?

**Comment by eirnym** [comment]
Btw, I'm not _against_ calling git, but I _prefer_ use a third-party plugin

**Pull request closed without merging**
