### PR TITLE
Android example using current plugin code

### PR DESCRIPTION
**Pull request by hannesa2**
Without comment, I'm not sure, which one is used. 
The one from maven, or the local source code one ?

### CODE REVIEW

**Comment by eirnym** [comment]
`plugins` section takes data from the `buildscript` section even you won't specify `classpath`. At least this is correct for plugins published to Gradle portal. 

I run a quick test locally and  maven line could be uncommented in all cases while plugins section is needed only when you remove the `includeBuild` line. 

The same is correct for a regular java project. 

We can switch back to `classpath` line (which was replaced by me by `plugins` section and basically do the same thing)

**Comment by hannesa2** [comment]
Independent of the solution to go, I would see a single point of truth.
For which one, I've no strong solution.

**Comment by eirnym** [comment]
I'd add `maven` line and leave the one of variant (with classpath or `plugins`).

Also README.md files in examples are important to describe the `includeBuild` line in settings.gradle.

_I'd love to have_ a separate `settings.gradle` (or some another specific initialization file) for examples though, but it could take some time to prepare it

**Comment by eirnym** [comment]
let's add a `classpath` for consistency

**Comment by eirnym** [comment]
what do you think?

**Comment by hannesa2** [comment]
I'm fine

**Comment by hannesa2** [comment]
To be honest, I'm confused now.
The main question is: 
Do we use Android example as demo using latest released version (this pull request #63), or 
do we use Android example to test current plugin implementation by code  ? #65

That's why we have to close one of them, this or #65

But there is a solution to have both, but first we should decide this question, to avoid more confusion

**Comment by eirnym** [comment]
now I see your confusion. 
I'd go with #65 without changes in `settings.gradle`, but adding an explanation to remove this line to have a real world example. I've checked quickly, that Gradle doesn't download a plugin in this case to it's cache, so we can use it in our tests as well. 

What's your opinion on this topic?

**Comment by hannesa2** [comment]
> Do we use Android example as demo using latest released version (this pull request #63), or
> do we use Android example to test current plugin implementation by code ? #65

**Sorry**, I made more confusion, I swapped variant A and B the right question are these:

Do we use Android example as demo using latest released version #65 , or
do we use Android example to test current plugin implementation by code ? (this pull request #63)

Please merge one and close the other one. Independent which version you go

**Comment by eirnym** [comment]
I released, that we can specify another settings.gradle just for testing. I'd create a PR for that

**Pull request closed without merging**
