### PR TITLE
Apply Spotless for consistent code formatting

### PR DESCRIPTION
**Pull request by jamietanna**
As a follow-up to #102, we want to make sure we have consistent code
style.

We can do this using Spotless, which has support for most of the
languages and file formats in this repo, as well as ???

### CODE REVIEW

**Comment by jamietanna** [comment]
Not sure if these issues are related? :grimacing:

**Review by eirnym — APPROVED** [review]

**Comment by eirnym** [comment]
@jamietanna currently demos are flaky. I'm going to fix them in new PR

**Comment by jamietanna** [comment]
Ah, flakey in what sense?

**Comment by eirnym** [comment]
Different groovy versions in gradle 6.x and 7.x

**Comment by eirnym** [comment]
Additionally, you can see `Compat.kt` for compatibility shims around various versions of Gradle

**Comment by hannesa2** [comment]
I opened Android sample and code format does not work properly

**Pull request merged**
