### PR TITLE
Support multiple executions per single project

### LINKED ISSUE #31: Possible to run with separate settings for different files?
More of a question than an actual issue: 

I was wondering if it is somehow possible to run with separate settings for different files? In my example, I have schemas that look a little bit different, but have overlapping names. As such, I need to prefix each of the generate pojos a bit differently. 

I have currenly resolved to using a bash script and the CLI like this

```
jsonschema2pojo -y Create -fdt -r -ut -tv 11 -303 -b -R -s src/main/resources/schemas/CREATE-Payload_Schema.json -t build/generated/sources/js2p -p com.example
jsonschema2pojo -y Update -fdt -r -ut -tv 11 -303 -b -s src/main/resources/schemas/UPDATE_Payload_Schema.json -t build/generated/sources/js2p -p com.example
jsonschema2pojo -y Read -fdt -r -ut -tv 11 -303 -b -s src/main/resources/schemas/READ_Response_Schema.json -t build/generated/sources/js2p -p com.example
```

This works but is giving us some headache as some developers or on a Windows machine.

### PR DESCRIPTION
**Pull request by eirnym**
closes #31

### CODE REVIEW

**Comment by hannesa2** [comment]
It would be great to make usage in our demo projects(s)

**Comment by eirnym** [comment]
I wrote tests for now, after release, I'd add examples to `demo` projects

**Comment by hannesa2** [comment]
Is there a reason why not add it now. It would help me to understand the usage and purpose

**Review by hannesa2 — APPROVED** [review]

**Comment by eirnym** [comment]
We made all examples as demo projects. This mean we can't use development plugin version (without adding `includeBuild` in `settings.gradle`). Thus changing them now will lead to compilation errors

If it's a question about about tests, I've added few more cases to `JavaTaskFunctionalTest` to cover various use-cases. Tests don't neglect the feature demonstration though

**Pull request merged**
